# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b22ba836615cf77575af382466e626e1b0bac49f9d5bfd5405bd716940d15ebbcbed2eb9a335ba63154b01578c1293ebac806a2a1658e217f430a851e266ef

test:
  secret_key_base: 0d1ecf90c509226108250ab5e5be9e8f6e2ba9c1204200ca989913e9444a29046c7184627211a960f7d505e3c7a2e9dcfcc7b3e2ecc0a6ecf474f22e6f9d1fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
